version: "3.3"
services:
  mongodb:
    image: mongo:5.0
    restart: always
    container_name: my_mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
    - "8080:8081"

  postgres:
    image: postgres:12.14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dst_airlines
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local

