version: "3.3"
services:
  mongodb:
    image: mongo:5.0
    restart: always
    container_name: my_mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network

  mongo-express:
    image: mongo-express
    container_name: my_mongo_express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/?authSource=admin
    ports:
      - "8080:8081"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - my_network

  postgres:
    image: postgres:12.14
    restart: always
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dst_airlines
    ports:
      - "8001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: unless-stopped
    #extra_hosts:
      #- "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
        - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
        - "8085:80"
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - my_network
    depends_on:
      - postgres
    restart: unless-stopped


  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: my_fastapi
    depends_on:
      - mongodb
      - postgres
    ports:
      - "8000:8000"
    networks:
      - my_network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dash
    container_name: my_dash
    depends_on:
      - mongodb
      - postgres
    ports:
      - "8050:8050"
    networks:
      - my_network

volumes:
  mongo-data:
  postgres-data:
  pgadmin:

networks:
  my_network:
    driver: bridge


