# Use a base image with Python 3.8 installed
FROM python:3.8-slim-buster
ENV platform='docker'
COPY . /dst_airlines/

RUN pip3 install -r /dst_airlines/requirements.txt
# Expose port 8050 for the dashboard
EXPOSE 8050
WORKDIR /dst_airlines/src
CMD ["python3", "dashboard_mongo.py"]